version: '3.8'

#networks:
#  neo4j-network:
#    driver: bridge

services:
# Neo4j
  neo4j:
    #image: bitnami/neo4j:latest
    image: neo4j:latest
    #networks:
    #  - neo4j-network
    ports:
      - 7473:7473 # HTTPS
      - 7475:7474 # HTTP
      - 7688:7687 # BOLT
    environment:
      #- NEO4J_dbms_security_procedures_unrestricted=apoc.*
      #- NEO4J_apoc_import_file_enabled=true
      #- NEO4J_apoc_export_file_enabled=true
      #- NEO4J_dbms_shell_enabled=true
      #  https://neo4j.com/docs/labs/neo4j-streams/current/docker/#neo4j_streams_docker
      #- NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      #- NEO4J_dbms_ssl_policy_https_client__auth=NONE
      #- NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      #- NEO4J_dbms_connector_https_advertised__address="localhost:7473" 
      #- NEO4J_dbms_connector_http_advertised__address="localhost:7475"
      #- NEO4J_dbms_connector_bolt_advertised__address="localhost:7688"
      - NEO4J_AUTH=neo4j/test
      - NEO4J_PLUGINS=["graph-data-science"]

    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/import

# anzograph
  anzograph:
    image: cambridgesemantics/anzograph:latest
    ports:
      - 8085:8080 # HTTP 
      - 8445:8443 # HTTPS
    volumes:
      - /opt/shared-files:/opt/shared-files

# BlazeGraph
  blazegraph:
    image: nawer/blazegraph
    ports:
      - 9999:9999
    environment:
        JAVA_XMS: 512m
        JAVA_XMX: 1g

# RDFox
  rdfoxgraph:
    image: oxfordsemantic/rdfox:latest
    ports:
      - 12110:12110
    volumes:
      - ./data:/data